image: node:lts

pipelines:
  branches:
    im/development:
      - step:
          caches:
            - node
          name: Build the React App
          script:
            - npm install
            - CI=false npm run build
          artifacts:
            - build/**
      - step:
          name: Deploy the build to Environment
          deployment: Development_ENV
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: 'build'
                ACL: 'public-read'
            - pipe: atlassian/aws-cloudfront-invalidate:0.3.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                DISTRIBUTION_ID: $CF_DISTRIBUTION_ID
